<?php

use Illuminate\Database\Seeder;

class ProductTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $products = [
                 ['barcode'=>'', 'name'=>'ABRAZADERA CU 1/2', 'sale_price'=>'190', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'ABRAZADERA GALVANIZADA 5/8 P/ CONDUIT', 'sale_price'=>'100', 'stock'=> '50'],
                 ['barcode'=>'', 'name'=>'ABRAZADERA HID 20MM', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'ABRAZADERA HID 25MM', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'ABRAZADERA METAL 1 1/4', 'sale_price'=>'990', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'ABRAZADERA METAL 1"', 'sale_price'=>'790', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'ABRAZADERA METAl nº 02 (1/2")', 'sale_price'=>'390', 'stock'=> '48'],
                 ['barcode'=>'', 'name'=>'ABRAZADERA METAL nº3 (3/4")', 'sale_price'=>'490', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'ABRAZADERA SANITARIA 110 M.M.', 'sale_price'=>'680', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'ABRAZADERA SANITARIA 40 M.M.', 'sale_price'=>'160', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'ABRAZADERA SANITARIA 50 M.M.', 'sale_price'=>'210', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'ABRAZADERA SANITARIA 75 M.M.', 'sale_price'=>'540', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'ACOPLE RAPIDO PLAST. LLAVE JARDIN 1/2', 'sale_price'=>'590', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'ADAPTADOR MANGUERA 3/4 - 1/2', 'sale_price'=>'590', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'ADAPTADOR TRIPLE ELECTRICO ', 'sale_price'=>'1990', 'stock'=> '4'],
                 ['barcode'=>'', 'name'=>'ADHESIVO PVC VINILIT 240cc', 'sale_price'=>'2780', 'stock'=> '4'],
                 ['barcode'=>'', 'name'=>'ADHESIVO PVC VINILIT 25cc', 'sale_price'=>'720', 'stock'=> '12'],
                 ['barcode'=>'', 'name'=>'ADHESIVO PVC VINILIT 60cc', 'sale_price'=>'1200', 'stock'=> '12'],
                 ['barcode'=>'', 'name'=>'ALAMBRE ELECTRICO  ROJO X MTS.', 'sale_price'=>'', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'ALAMBRE ELECTRICO BLANCO X MTS.', 'sale_price'=>'', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'ALAMBRE ELECTRICO VERDE X MTS', 'sale_price'=>'', 'stock'=> '100'],
                 ['barcode'=>'7807354071037', 'name'=>'ALARGADOR 3 MTS 5 POSICIONES ', 'sale_price'=>'8500', 'stock'=> '3'],
                 ['barcode'=>'', 'name'=>'ALCAYATA C/ MACHO 6"', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'2003581062100', 'name'=>'ALDABAS 2"', 'sale_price'=>'', 'stock'=> '100'],
                 ['barcode'=>'2003581063100', 'name'=>'ALDABAS 3"', 'sale_price'=>'', 'stock'=> '100'],
                 ['barcode'=>'15980942560000', 'name'=>'ALDABAS 4"', 'sale_price'=>'', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'ALICATE DE CORTE 6"', 'sale_price'=>'1990', 'stock'=> '6'],
                 ['barcode'=>'', 'name'=>'ALICATE PUNTA 6"', 'sale_price'=>'1990', 'stock'=> '6'],
                 ['barcode'=>'', 'name'=>'ALICATE UNIVERSAL 6"', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'ALICATE UNIVERSAL 8"', 'sale_price'=>'2400', 'stock'=> '6'],
                 ['barcode'=>'6931598209732', 'name'=>'AMARRA CABLES 2,5 X 160 C/U', 'sale_price'=>'30', 'stock'=> '100'],
                 ['barcode'=>'6931598209749', 'name'=>'AMARRA CABLES 4,8 X 200 C/U', 'sale_price'=>'50', 'stock'=> '100'],
                 ['barcode'=>'6931598217683', 'name'=>'AMARRA CABLES 4,8 X 300 C/U', 'sale_price'=>'70', 'stock'=> '200'],
                 ['barcode'=>'6931598217690', 'name'=>'AMARRA CABLES 4,8 X 400 C/U', 'sale_price'=>'100', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'ANZUELO Nº 1', 'sale_price'=>'100', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'ANZUELO Nº 2', 'sale_price'=>'100', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'ANZUELO Nº 3', 'sale_price'=>'100', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'ANILLA CROMADA 12MM', 'sale_price'=>'100', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'ARCO SIERRA 8-12"', 'sale_price'=>'1990', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'BARRA CROMADA 1,20MT', 'sale_price'=>'1090', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'BARRA CROMADA 1,5MT', 'sale_price'=>'1590', 'stock'=> '24'],
                 ['barcode'=>'', 'name'=>'BARRA CROMADA 2MT', 'sale_price'=>'1990', 'stock'=> '24'],
                 ['barcode'=>'', 'name'=>'BASE RECTA LOZA', 'sale_price'=>'690', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'BISAGRAS 1 1/2" C/U', 'sale_price'=>'210', 'stock'=> '24'],
                 ['barcode'=>'10001000131024', 'name'=>'BISAGRAS 2 1/2" C/U', 'sale_price'=>'290', 'stock'=> '24'],
                 ['barcode'=>'10001000138024', 'name'=>'BISAGRAS 2" C/U', 'sale_price'=>'250', 'stock'=> '24'],
                 ['barcode'=>'10001000062024', 'name'=>'BISAGRAS 3 1/2 X 3 1/2" C/U', 'sale_price'=>'890', 'stock'=> '24'],
                 ['barcode'=>'10015195144024', 'name'=>'BISAGRAS 3X3" C/U', 'sale_price'=>'690', 'stock'=> '22'],
                 ['barcode'=>'10015042063024', 'name'=>'BISAGRAS 4" C/U', 'sale_price'=>'890', 'stock'=> '24'],
                 ['barcode'=>'10001000064024', 'name'=>'BRAZO DUCHA IMPORTADO', 'sale_price'=>'2290', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'BROCA CONCRETO 10MM', 'sale_price'=>'1490', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'BROCA CONCRETO 6 MM', 'sale_price'=>'950', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'BROCA CONCRETO 5MM', 'sale_price'=>'750', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'BROCA CONCRETO 8MM', 'sale_price'=>'1290', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'BROCA MADERA 10MM', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'BROCA MADERA 4MM', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'BROCA MADERA 6MM', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'BROCA MADERA 8MM', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'BROCA METAL 10MM', 'sale_price'=>'2590', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'BROCA METAL 3.5MM', 'sale_price'=>'590', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'BROCA METAL 4.5MM', 'sale_price'=>'750', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'BROCA METAL 4MM', 'sale_price'=>'650', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'BROCA METAL 5.5MM', 'sale_price'=>'1250', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'BROCA METAL 5MM', 'sale_price'=>'850', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'BROCA METAL 6MM', 'sale_price'=>'1350', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'BROCA METAL 8MM', 'sale_price'=>'1990', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'BROCHA CONDECORA 1"', 'sale_price'=>'490', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'BROCHA CONDECORA 11/2', 'sale_price'=>'590', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'BROCHA CONDECORA 2"', 'sale_price'=>'790', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'BROCHA CONDECORA 3"', 'sale_price'=>'1190', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'BROCHA CONDECORA 4"', 'sale_price'=>'1520', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'BUJE HID CORTO 32x25', 'sale_price'=>'190', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'BUJE HID LARGO 25x20', 'sale_price'=>'280', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'BUJE HID LARGO 32x25', 'sale_price'=>'280', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'BUJE HID. CORTO 25x20', 'sale_price'=>'100', 'stock'=> '50'],
                 ['barcode'=>'', 'name'=>'BUJE HID. CORTO 32x20', 'sale_price'=>'190', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'BUSCAPOLO TRUPPER 140 MM', 'sale_price'=>'990', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'BUSHING BRONCE HI-HE 1/2', 'sale_price'=>'1490', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'BUSHING BRONCE HI-HE 1/2X3/8', 'sale_price'=>'550', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'BUSHING BRONCE HI-HE 3/4X 1/2', 'sale_price'=>'1190', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'CACHIMBA RECTA HI 1/2', 'sale_price'=>'1100', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'CAJA DERIVACION EMBUTIDA', 'sale_price'=>'250', 'stock'=> '20'],
                 ['barcode'=>'', 'name'=>'CAJA DERIVACION SOBREPUESTA', 'sale_price'=>'410', 'stock'=> '30'],
                 ['barcode'=>'', 'name'=>'CAJA TIPO CHIQUI', 'sale_price'=>'950', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'CAMARA CARRETILLA', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'CANALETA ELECTRICA 20 X 10 MM X 2 MTS', 'sale_price'=>'370', 'stock'=> '50'],
                 ['barcode'=>'', 'name'=>'CANCAMO ABIERTO Nº1', 'sale_price'=>'50', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'CANCAMO ABIERTO Nº3', 'sale_price'=>'70', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'CANCAMO ABIERTO Nº5 ', 'sale_price'=>'90', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'CANCAMO ABIERTO Nº9', 'sale_price'=>'150', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'CANCAMO CERRADO Nº0', 'sale_price'=>'40', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'CANCAMO CERRADO Nº1', 'sale_price'=>'50', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'CANCAMO CERRADO Nº3', 'sale_price'=>'70', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'CANCAMO CERRADO Nº5 ', 'sale_price'=>'90', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'CANCAMO CERRADO Nº9', 'sale_price'=>'150', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'CANDADO DE SEGURIDAD G.STAR 40 MM', 'sale_price'=>'2750', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'CANDADO DE SEGURIDAD G.STAR 50 MM ', 'sale_price'=>'3200', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'CANDADO ECONOMICO 25MM', 'sale_price'=>'390', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'CANDADO ECONOMICO 32MM', 'sale_price'=>'590', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'CANDADO ECONOMICO 38MM', 'sale_price'=>'690', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'CANDADO ECONOMICO 50MM', 'sale_price'=>'990', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'CANDADO TRICIRCLE 25MM', 'sale_price'=>'1490', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'CANDADO TRICIRCLE 32MM', 'sale_price'=>'2290', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'CANDADO TRICIRCLE 38MM', 'sale_price'=>'2790', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'CANDADO TRICIRCLE 50MM', 'sale_price'=>'4990', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'CAÑERIA COBRE TIPO L 1/2X6MTS', 'sale_price'=>'17200', 'stock'=> '3'],
                 ['barcode'=>'', 'name'=>'CAÑERIA COBRE TIPO L 1/2XMTS', 'sale_price'=>'3350', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'CAÑERIA COBRE TIPO M 1/2X6MTS', 'sale_price'=>'14200', 'stock'=> '5'],
                 ['barcode'=>'', 'name'=>'CAÑERIA COBRE TIPO M 1/2XMTS', 'sale_price'=>'2850', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'CAPUCHON GOMA 40X32', 'sale_price'=>'290', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'CAPUCHON GOMA 50X40', 'sale_price'=>'390', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'CARRETILLA CORRIENTE ', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'CELOSIA PLASTICA 20X20', 'sale_price'=>'1390', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'CEMENTO X KG', 'sale_price'=>'250', 'stock'=> '42'],
                 ['barcode'=>'', 'name'=>'CEMENTO X SACO ', 'sale_price'=>'4990', 'stock'=> '14'],
                 ['barcode'=>'', 'name'=>'CERRADURA ', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'CERRADURA POMO INTERIOR CHINA', 'sale_price'=>'4390', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'CERRADURA POMO INTERIOR CHINA', 'sale_price'=>'4390', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'CERRADURA SOBREPONER  LIOI', 'sale_price'=>'11990', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'CHINCHE DORADO X 50 UNID.', 'sale_price'=>'250', 'stock'=> ''],
                 ['barcode'=>'6953938200179', 'name'=>'CINCEL 10"', 'sale_price'=>'1690', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'CINTA ENMASCARAR 18 MM', 'sale_price'=>'790', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'CINTA ENMASCARAR 24 MM', 'sale_price'=>'990', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'CINTA ENMASCARAR 36 MM', 'sale_price'=>'1490', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'CLAVO CORRIENTE 1 1/2', 'sale_price'=>'1390', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'CLAVO CORRIENTE 1"', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'CLAVO CORRIENTE 2 1/2 ', 'sale_price'=>'1190', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'CLAVO CORRIENTE 2"', 'sale_price'=>'1190', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'CLAVO CORRIENTE 21/2', 'sale_price'=>'1190', 'stock'=> '25'],
                 ['barcode'=>'', 'name'=>'CLAVO CORRIENTE 3"', 'sale_price'=>'1190', 'stock'=> '50'],
                 ['barcode'=>'', 'name'=>'CLAVO CORRIENTE 4"', 'sale_price'=>'1190', 'stock'=> '50'],
                 ['barcode'=>'', 'name'=>'CLAVO TECHO 13/4', 'sale_price'=>'2200', 'stock'=> '25'],
                 ['barcode'=>'', 'name'=>'CLAVO TECHO 21/2', 'sale_price'=>'2690', 'stock'=> '25'],
                 ['barcode'=>'', 'name'=>'CLAVO VOLCANITA 1 5/8', 'sale_price'=>'1590', 'stock'=> '25'],
                 ['barcode'=>'', 'name'=>'CODO BRONCE SO-HE 1/2', 'sale_price'=>'690', 'stock'=> '20'],
                 ['barcode'=>'', 'name'=>'CODO BRONCE SO-HE 3/4', 'sale_price'=>'1230', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'CODO BRONCE SO-HI 1/2', 'sale_price'=>'750', 'stock'=> '20'],
                 ['barcode'=>'', 'name'=>'CODO BRONCE SO-HI 3/4', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'CODO BRONCE SO-SO 1/2', 'sale_price'=>'590', 'stock'=> '50'],
                 ['barcode'=>'', 'name'=>'CODO BRONCE SO-SO 3/4', 'sale_price'=>'930', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'CODO BRONCE SO-SO 3/4X1/2', 'sale_price'=>'450', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'CODO CACHIMBA 1/2 C/ESPIGA ', 'sale_price'=>'1390', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'CODO COBRE 1/2X90', 'sale_price'=>'390', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'CODO COBRE 3/4X1/2', 'sale_price'=>'590', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'CODO HID 20X90', 'sale_price'=>'200', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'CODO HID 25X90', 'sale_price'=>'270', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'CODO HID 32X90', 'sale_price'=>'320', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'CODO HID HI 20 X 1/2', 'sale_price'=>'300', 'stock'=> '60'],
                 ['barcode'=>'', 'name'=>'CODO PLANZA 1/2', 'sale_price'=>'150', 'stock'=> '20'],
                 ['barcode'=>'', 'name'=>'CODO PLANZA HI 1/2', 'sale_price'=>'300', 'stock'=> '20'],
                 ['barcode'=>'', 'name'=>'CODO SANIT 110X45', 'sale_price'=>'1490', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'CODO SANIT 110X90', 'sale_price'=>'1690', 'stock'=> '20'],
                 ['barcode'=>'', 'name'=>'CODO SANIT 40X45', 'sale_price'=>'390', 'stock'=> '20'],
                 ['barcode'=>'', 'name'=>'CODO SANIT 40X90', 'sale_price'=>'290', 'stock'=> '50'],
                 ['barcode'=>'', 'name'=>'CODO SANIT 50X45', 'sale_price'=>'440', 'stock'=> '20'],
                 ['barcode'=>'', 'name'=>'CODO SANIT 50X90', 'sale_price'=>'490', 'stock'=> '50'],
                 ['barcode'=>'', 'name'=>'CODO SANIT 75X45', 'sale_price'=>'690', 'stock'=> '30'],
                 ['barcode'=>'', 'name'=>'CODO SANIT 75X90', 'sale_price'=>'790', 'stock'=> '30'],
                 ['barcode'=>'', 'name'=>'COLETO CARPINTERO LONA ', 'sale_price'=>'4990', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'COMB. TINA/DUCHA GOLBRIGHT METAL ', 'sale_price'=>'14990', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'COMB.TINA/DUCHA  CHINA', 'sale_price'=>'19350', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'COMBINACION LAVALATOS T/V GOLBRIGTH ', 'sale_price'=>'8990', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'COMBINACION LAVAPLATOS  660', 'sale_price'=>'16300', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'COMBINACION LAVAPLATOS ISABELLA ', 'sale_price'=>'8990', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'COMBINACION LAVAPLATOS PLANA METAL', 'sale_price'=>'12990', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'CONECTOR RG 6 TV CABLE ', 'sale_price'=>'60', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'COPLA BRONCE HI-HI 1/2', 'sale_price'=>'1350', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'COPLA BRONCE SO 3/4 X 1/2', 'sale_price'=>'690', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'COPLA BRONCE SO-SO 1/2', 'sale_price'=>'270', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'COPLA BRONCE SO-SO 3/4', 'sale_price'=>'990', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'COPLA COBRE 1/2', 'sale_price'=>'190', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'COPLA COBRE 3/4', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'COPLA COBRE 3/4/X1/2', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'COPLA HID 20MM', 'sale_price'=>'100', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'COPLA HID 25MM', 'sale_price'=>'180', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'COPLA HID 32MM', 'sale_price'=>'240', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'COPLA SANIT 110MM', 'sale_price'=>'1290', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'COPLA SANIT 110X40MM', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'COPLA SANIT 110X50MM', 'sale_price'=>'890', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'COPLA SANIT 110X75MM', 'sale_price'=>'990', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'COPLA SANIT 40MM', 'sale_price'=>'290', 'stock'=> '20'],
                 ['barcode'=>'', 'name'=>'COPLA SANIT 50MM', 'sale_price'=>'390', 'stock'=> '20'],
                 ['barcode'=>'', 'name'=>'COPLA SANIT 50X40MM', 'sale_price'=>'290', 'stock'=> '20'],
                 ['barcode'=>'', 'name'=>'COPLA SANIT 75MM', 'sale_price'=>'590', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'COPLA SANIT 75X50MM', 'sale_price'=>'490', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'CUCHARA ALBAÑIL 6"', 'sale_price'=>'1290', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'CUCHILLO CARTONERO ', 'sale_price'=>'1390', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'CUCHILLO CARTONERO ECONOMICO', 'sale_price'=>'490', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'CUCHILLO CARTONERO ECONOMICO ', 'sale_price'=>'490', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'CURVA CONDUIT 16 MM', 'sale_price'=>'100', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'CURVA CONDUIT 20 MM ', 'sale_price'=>'130', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'DADO MAGNETICO 5/16', 'sale_price'=>'1190', 'stock'=> '10'],
                 ['barcode'=>'25349168480010', 'name'=>'DASAGUE METAL 1 1/4', 'sale_price'=>'3990', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'DESAGUE LAVAPLATO 1 1/2 C/ REB', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'DESAGUE LAVAPLATO PLAST 1 1/2 C/COLA ', 'sale_price'=>'1190', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'DESAGUE LAVATORIO PLAST 1 1/4 C/COLA', 'sale_price'=>'1290', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'DESAGUE METAL 1 1/2', 'sale_price'=>'3660', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'DESTORCEDORDE NYLON Nº 12', 'sale_price'=>'100', 'stock'=> '144'],
                 ['barcode'=>'', 'name'=>'DESAGUE TINA C/REB Y SIFON ', 'sale_price'=>'4990', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'DESTORNILLADOR CRUZ 1/4X4', 'sale_price'=>'1590', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'DESTORNILLADOR CRUZ 3/16X4 FODEX', 'sale_price'=>'590', 'stock'=> '12'],
                 ['barcode'=>'6931598212876', 'name'=>'DESTORNILLADOR CRUZ 3/16X4 UYUS', 'sale_price'=>'1100', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'DESTORNILLADOR PALETA 1/4X4', 'sale_price'=>'1290', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'DESTORNILLADOR PALETA 3/16X4', 'sale_price'=>'990', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'DESTORNILLADOR PALETA 3/16X4 FODEX', 'sale_price'=>'590', 'stock'=> '12'],
                 ['barcode'=>'6931598212886', 'name'=>'DIABLITO 18"', 'sale_price'=>'2500', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'DIABLITO 24"', 'sale_price'=>'3100', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'DISCO CORTE ACERO INOX 4 1/2', 'sale_price'=>'790', 'stock'=> '110'],
                 ['barcode'=>'', 'name'=>'DISCO CORTE ACERO INOX 7 1/4', 'sale_price'=>'1890', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'DISCO CORTE METAL 4 1/2', 'sale_price'=>'790', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'DISCO CORTE METAL 7 1/4', 'sale_price'=>'1190', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'DISCO DESBASTE  4 1/2', 'sale_price'=>'1590', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'DISCO DESBASTE 7 1/4', 'sale_price'=>'2990', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'DISCO DIAMANTADO 4 1/2', 'sale_price'=>'2590', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'DISCO DIAMANTADO 7 1/4', 'sale_price'=>'4890', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'DISCO LIJA 4 1/2 GR 100', 'sale_price'=>'470', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'DISCO LIJA 4 1/2 GR 120', 'sale_price'=>'470', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'DISCO LIJA 4 1/2 GR 60', 'sale_price'=>'470', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'DISCO LIJA 4 1/2 GR 80', 'sale_price'=>'470', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'DISCO SIERRA 4 1/2X24 DTS', 'sale_price'=>'2990', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'DISCO SIERRA 4 1/2X40 DTS', 'sale_price'=>'3280', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'DISCO SIERRA 7 1/4X 24 DTS', 'sale_price'=>'3600', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'DISCO SIERRA 7 1/4X 40 DTS', 'sale_price'=>'4190', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'DISCO SUJ.VELCRO GR 100', 'sale_price'=>'220', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'DISCO SUJ.VELCRO GR 120 ', 'sale_price'=>'220', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'DISCO SUJ.VELCRO GR 60', 'sale_price'=>'220', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'DISCO SUJ.VELCRO GR 80', 'sale_price'=>'220', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'ELECTRODO 6011 1/8', 'sale_price'=>'2590', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'ELECTRODO 6011 3/32', 'sale_price'=>'2690', 'stock'=> '20'],
                 ['barcode'=>'', 'name'=>'ENCHUFE HEMBRA VOLANTE 2P + T GEWIS ', 'sale_price'=>'1490', 'stock'=> '15'],
                 ['barcode'=>'', 'name'=>'ENCHUFE MACHO VOLANTE 3P + T GEWIS', 'sale_price'=>'1350', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'ENCHUFE MACHO VOLANTE 2P + T GEWIS', 'sale_price'=>'1250', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'ENCHUFE PARED DOBLE  9/12 10AMP.', 'sale_price'=>'1490', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'ENCHUFE PARED TRIPLE 9/12 10 AMP.', 'sale_price'=>'1990', 'stock'=> '6'],
                 ['barcode'=>'', 'name'=>'ENCHUFE PARED SIMPLE 9/12 10AMP.', 'sale_price'=>'890', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'ESCOBILLA ACERO S/MANGO', 'sale_price'=>'690', 'stock'=> '12'],
                 ['barcode'=>'', 'name'=>'ESCOBILLA REDONDA 2 PZAS ', 'sale_price'=>'1590', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'ESCOBILLA REDONDA 3 PZAS ', 'sale_price'=>'1790', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'ESCOBILLA REDONDA 5 PZAS', 'sale_price'=>'2390', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'ESCUADRA CARPINTERA 10"', 'sale_price'=>'1140', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'ESCUADRA CARPINTERA 12"', 'sale_price'=>'1240', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'ESCUADRA CARPINTERA 6"', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'ESCUADRA CARPINTERA 8"', 'sale_price'=>'1190', 'stock'=> '12'],
                 ['barcode'=>'', 'name'=>'ESCUADRA REPISA 4X5', 'sale_price'=>'300', 'stock'=> '24'],
                 ['barcode'=>'', 'name'=>'ESCUADRA REPISA 6X8', 'sale_price'=>'500', 'stock'=> '24'],
                 ['barcode'=>'', 'name'=>'ESCUADRA SILLA 1 1/2"', 'sale_price'=>'120', 'stock'=> '36'],
                 ['barcode'=>'', 'name'=>'ESCUADRA SILLA 1"', 'sale_price'=>'100', 'stock'=> '36'],
                 ['barcode'=>'', 'name'=>'ESCUADRA SILLA 2 1/2"', 'sale_price'=>'250', 'stock'=> '36'],
                 ['barcode'=>'', 'name'=>'ESCUADRA SILLA 2"', 'sale_price'=>'180', 'stock'=> '36'],
                 ['barcode'=>'', 'name'=>'ESPATULA 100MM', 'sale_price'=>'1100', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'ESPATULA 140MM', 'sale_price'=>'720', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'ESPATULA 40MM (1 1/2)', 'sale_price'=>'260', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'ESPATULA 50MM (2)', 'sale_price'=>'850', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'ESPATULA 70MM ', 'sale_price'=>'420', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'ESPATULA 80MM (3)', 'sale_price'=>'990', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'ESPUMA POLIURETANA 750ML', 'sale_price'=>'3580', 'stock'=> '12'],
                 ['barcode'=>'', 'name'=>'FAPPER C/CADENA', 'sale_price'=>'990', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'FIELTRO LISO 10/16 MTS', 'sale_price'=>'4990', 'stock'=> '6'],
                 ['barcode'=>'', 'name'=>'FIELTRO LISO 10/40 MTS', 'sale_price'=>'7100', 'stock'=> '6'],
                 ['barcode'=>'', 'name'=>'FLANGE P/BARRA 1/2 (PAR)', 'sale_price'=>'550', 'stock'=> '20'],
                 ['barcode'=>'', 'name'=>'FLEXIBLE AGUA HI-HE 25 CM', 'sale_price'=>'1490', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'FLEXIBLE AGUA HI-HE 30 CM', 'sale_price'=>'1590', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'FLEXIBLE AGUA HI-HE 35 CM', 'sale_price'=>'1890', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'FLEXIBLE AGUA HI-HE 40 CM', 'sale_price'=>'1990', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'FLEXIBLE AGUA HI-HI 25 CM', 'sale_price'=>'1490', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'FLEXIBLE AGUA HI-HI 30 CM', 'sale_price'=>'1290', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'FLEXIBLE AGUA HI-HI 35 CM', 'sale_price'=>'1890', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'FLEXIBLE AGUA HI-HI 40 CM ', 'sale_price'=>'1990', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'FLEXIBLE DUCHA 1,5 MTS', 'sale_price'=>'2990', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'FLEXIBLE DUCHA 2 MTS', 'sale_price'=>'3490', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'FLEXIBLE ESTANQUE 30 CM', 'sale_price'=>'1990', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'FLEXIBLE GAS 1/2X3/8 IZQX100 CM', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'FLEXIBLE GAS 1/2X7/8 X100 CM', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'FLEXIBLE MONOMANDO 40 CM', 'sale_price'=>'1850', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'FORMON 1"', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'FORMON 1/2 ', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'FORMON 3/4', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'GAS BUTANO ', 'sale_price'=>'990', 'stock'=> '72'],
                 ['barcode'=>'', 'name'=>'GAS BUTANO CILINDRICO ', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'GOLILLA PLANA CORRIENTE 1/2', 'sale_price'=>'50', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'GOLILLA PLANA CORRIENTE 1/4', 'sale_price'=>'20', 'stock'=> '400'],
                 ['barcode'=>'', 'name'=>'GOLILLA PLANA CORRIENTE 3/4', 'sale_price'=>'100', 'stock'=> '400'],
                 ['barcode'=>'', 'name'=>'GOLILLA PLANA CORRIENTE 3/8', 'sale_price'=>'40', 'stock'=> '400'],
                 ['barcode'=>'', 'name'=>'GOLILLA PLANA CORRIENTE 5/16', 'sale_price'=>'20', 'stock'=> '400'],
                 ['barcode'=>'', 'name'=>'GOLILLA PRESION 1/2', 'sale_price'=>'30', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'GOLILLA PRESION 1/4', 'sale_price'=>'10', 'stock'=> '200'],
                 ['barcode'=>'', 'name'=>'GOLILLA PRESION 3/4', 'sale_price'=>'140', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'GOLILLA PRESION 3/8', 'sale_price'=>'20', 'stock'=> '200'],
                 ['barcode'=>'', 'name'=>'GOLILLA PRESION 5/16', 'sale_price'=>'20', 'stock'=> '200'],
                 ['barcode'=>'', 'name'=>'GOMA LLAVE 1/2 NEGRA', 'sale_price'=>'80', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'GOMA LLAVE 1/2 ROJA', 'sale_price'=>'80', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'GOTITA', 'sale_price'=>'2450', 'stock'=> '6'],
                 ['barcode'=>'', 'name'=>'GRAPA COAXIAL NEGRO', 'sale_price'=>'30', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'GRAPA ELECTRICA 3/4', 'sale_price'=>'20', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'GRAPA ELECTRICA 5/8 ', 'sale_price'=>'20', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'GRATA ONDULADA  4"', 'sale_price'=>'3490', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'GRATA ONDULADA 3"', 'sale_price'=>'1890', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'GRATA TRENZADA  4"', 'sale_price'=>'3490', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'GRATA TRENZADA 3"', 'sale_price'=>'2500', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'GUANTE ANSELL', 'sale_price'=>'1150', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'GUANTE CABRETILLA S/FORRO ', 'sale_price'=>'2650', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'GUANTE CROMO CONDUCTOR ', 'sale_price'=>'2490', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'GUANTE DESCARNE REFORSADO ', 'sale_price'=>'1790', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'GUANTE NITRILO MULTIUSO', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'GUANTE PIGMENTADO PAR', 'sale_price'=>'300', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'GUANTE SOLDADOR ', 'sale_price'=>'3550', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'HACHA 4 1/2 LIBRAS', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'HACHA MANO 700', 'sale_price'=>'5990', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'HILO IZQUERDO ', 'sale_price'=>'990', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'HOJA SIERRA ', 'sale_price'=>'990', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'HOJA SIERRA ECONOMICA UYUS', 'sale_price'=>'490', 'stock'=> '24'],
                 ['barcode'=>'', 'name'=>'HUINCHA  EMBALAR  CAFÉ', 'sale_price'=>'450', 'stock'=> '12'],
                 ['barcode'=>'', 'name'=>'HUINCHA AISLADORA 10 MTS', 'sale_price'=>'490', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'HUINCHA AISLADORA 20 MTS', 'sale_price'=>'1490', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'HUINCHA AISLADORA 5 MTS', 'sale_price'=>'490', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'HUINCHA EMBALAR TRANSPARENTE ', 'sale_price'=>'450', 'stock'=> '11'],
                 ['barcode'=>'', 'name'=>'HUINCHA MEDIR 3 MTS', 'sale_price'=>'1390', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'HUINCHA MEDIR 5 MTS', 'sale_price'=>'1980', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'HUINCHA MEDIR 7,5 MTS', 'sale_price'=>'2990', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'INTERRUPTOR SIMPLE', 'sale_price'=>'850', 'stock'=> '20'],
                 ['barcode'=>'', 'name'=>'INTERRUPTOR VOLANTE ', 'sale_price'=>'990', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'JUEGO DUCHA A-47', 'sale_price'=>'3690', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'JUEGO LLAVE ALLEN 10 PZAS', 'sale_price'=>'1100', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'KIT ANCLAJE WC', 'sale_price'=>'890', 'stock'=> '34'],
                 ['barcode'=>'', 'name'=>'LAPIZ CARPINTERO ', 'sale_price'=>'590', 'stock'=> '4'],
                 ['barcode'=>'', 'name'=>'LAPIZ CARPINTERO  UYUS', 'sale_price'=>'390', 'stock'=> '36'],
                 ['barcode'=>'', 'name'=>'LENTE POLICARBONATO TRANSPARENTE', 'sale_price'=>'590', 'stock'=> '12'],
                 ['barcode'=>'', 'name'=>'LIENZA CARPINTERA BLANCA-NEGRA X 200MTS.', 'sale_price'=>'1000', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'LIJA AL AGUA GR ', 'sale_price'=>'190', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'LIJA AL AGUA GR 100', 'sale_price'=>'190', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'LIJA AL AGUA GR 180', 'sale_price'=>'190', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'LIJA AL AGUA GR 280', 'sale_price'=>'190', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'LIJA AL AGUA GR 500', 'sale_price'=>'190', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'LIJA AL AGUA GR 80', 'sale_price'=>'190', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'LIJA MADERA GR', 'sale_price'=>'150', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'LIJA MADERA GR 100', 'sale_price'=>'150', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'LIJA MADERA GR 120', 'sale_price'=>'150', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'LIJA MADERA GR 150', 'sale_price'=>'150', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'LIJA MADERA GR 180', 'sale_price'=>'150', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'LIJA MADERA GR 240', 'sale_price'=>'150', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'LIJA MADERA GR 40', 'sale_price'=>'150', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'LIJA MADERA GR 50', 'sale_price'=>'150', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'LIJA MADERA GR 80 ', 'sale_price'=>'150', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'LIJA METAL GR ', 'sale_price'=>'380', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'LIJA METAL GR 100', 'sale_price'=>'380', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'LIJA METAL GR 120', 'sale_price'=>'380', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'LIJA METAL GR 180', 'sale_price'=>'380', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'LIJA METAL GR 40', 'sale_price'=>'380', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'LIJA METAL GR 60', 'sale_price'=>'380', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'LIJA METAL GR 80', 'sale_price'=>'380', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'LIMA MOTOSIERRA 3/16 ', 'sale_price'=>'1490', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'LIMA MOTOSIERRA 7/32', 'sale_price'=>'1490', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'LIMA PLANA 10"', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'LIMA PLANA 6"', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'LIMA PLANA 8"', 'sale_price'=>'3920', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'LIMA SERRUCHO 4 1/2', 'sale_price'=>'3990', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'LIQUIDO FRENO WAGNER', 'sale_price'=>'3390', 'stock'=> '6'],
                 ['barcode'=>'', 'name'=>'LLANA DENTADA (CHICO)', 'sale_price'=>'1690', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'LLANA DENTADA (GRANDE)', 'sale_price'=>'2390', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'LLANA LISA ', 'sale_price'=>'2180', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'LLAVE ANGULAR C/FLEX 25 CM', 'sale_price'=>'1990', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'LLAVE ANGULAR C/FLEX 30 CM ', 'sale_price'=>'2690', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'LLAVE ANGULAR C/FLEX 35 CM', 'sale_price'=>'2990', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'LLAVE ANGULAR HE-HE 1/2', 'sale_price'=>'2900', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'LLAVE FRANCESA 10"', 'sale_price'=>'4690', 'stock'=> '6'],
                 ['barcode'=>'', 'name'=>'LLAVE FRANCESA 12"', 'sale_price'=>'5990', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'LLAVE FRANCESA 6"', 'sale_price'=>'2790', 'stock'=> '6'],
                 ['barcode'=>'', 'name'=>'LLAVE FRANCESA 8"', 'sale_price'=>'3290', 'stock'=> '6'],
                 ['barcode'=>'', 'name'=>'LLAVE GAS C/TUERCA 1/2', 'sale_price'=>'3490', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'LLAVE JARDIN HE 1/2', 'sale_price'=>'2250', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'LLAVE JARDIN HE 3/4', 'sale_price'=>'3540', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'LLAVE LAVADORA 1/2X3/4', 'sale_price'=>'3990', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'LLAVE LAVAPLATO CUELLO CISNE C/ RAP', 'sale_price'=>'4990', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'LLAVE LAVATORIO ABS CHINA', 'sale_price'=>'2390', 'stock'=> '6'],
                 ['barcode'=>'', 'name'=>'LLAVE PASO CAMPANA 1/2', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'LLAVE PASO SO-SO 1/2', 'sale_price'=>'1690', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'LLAVE PASO SO-SO 3/4', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'LLAVE PASO SUP CROMADA 1/2', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'LLAVE PUNTA CORONA 10MM', 'sale_price'=>'690', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'LLAVE PUNTA CORONA 11MM', 'sale_price'=>'850', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'LLAVE PUNTA CORONA 12MM', 'sale_price'=>'850', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'LLAVE PUNTA CORONA 13MM', 'sale_price'=>'890', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'LLAVE PUNTA CORONA 15MM', 'sale_price'=>'1190', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'LLAVE PUNTA CORONA 17MM', 'sale_price'=>'1290', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'LLAVE PUNTA CORONA 19MM', 'sale_price'=>'1590', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'LLAVE PUNTA CORONA 21MM', 'sale_price'=>'1690', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'LLAVE PUNTA CORONA 24MM', 'sale_price'=>'1990', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'LLAVE PUNTA CORONA 8MM', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'LLAVE PUNTA CORONA 9MM', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'LUBRICANTE MULTIUSO 250ML.', 'sale_price'=>'2090', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'MANGO CHICHARRA DE 1/2', 'sale_price'=>'4500', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'MANGO DUCHA CROMADO ', 'sale_price'=>'1360', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'MANGUERA GAS', 'sale_price'=>'530', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'MANGUERA NIVEL 1/2XMTS', 'sale_price'=>'330', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'MANGUERA RIEGO 1/2XMTS', 'sale_price'=>'320', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'MANILLA ESTANQUE CROMADA', 'sale_price'=>'850', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'MARTILLO CARPINTERO 27MM M/FIBRA ', 'sale_price'=>'3990', 'stock'=> '6'],
                 ['barcode'=>'', 'name'=>'MARTILLO CARPINTERO 27MM M/MADERA', 'sale_price'=>'3990', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'MARTILLO CARPINTERO 27MM M/METAL', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'MASCARILLA DESECHABLE REDONDA', 'sale_price'=>'120', 'stock'=> '50'],
                 ['barcode'=>'', 'name'=>'MASILLA MAGICA 350 GRS', 'sale_price'=>'2990', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'MASILLA MAGICA 700 GRS', 'sale_price'=>'6690', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'MEDIDOR DE AGUA 1/2 R.D ', 'sale_price'=>'24890', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'MODULO INTERRUPTOR C/PLACA DOBLE', 'sale_price'=>'1690', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'MODULO INTERRUPTOR C/PLACA SIMPLE ', 'sale_price'=>'1190', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'MODULO INTERRUPTOR C/PLACA TRIPLE ', 'sale_price'=>'2290', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'MODULO Y PLACA ELECTRICO ENCHUFE DOBLE ', 'sale_price'=>'1590', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'MODULO Y PLACA ELECTRICO ENCHUFE SIMPLE ', 'sale_price'=>'1190', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'MODULO Y PLACA ELECTRICO ENCHUFE TRIPLE ', 'sale_price'=>'2290', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'MONOMANDO LAVAPLATO VERTICAL', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'MONOMANDO LAVAPLATO VERTICAL COLOMBA', 'sale_price'=>'11990', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'MONOMANDO LAVATORIO', 'sale_price'=>'11990', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'MONOMANDO LAVATORIO COLOMBA', 'sale_price'=>'9990', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'MONOMANDO TINA-DUCHA', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'MONOMANDO TINA-DUCHA PESADO', 'sale_price'=>'15800', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'NEUMATICO + CAMARA CARRETILLA', 'sale_price'=>'5990', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'NEUMATICO CARRETILLA (COMPLETO)', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'NIPLE BRONCE HE-HE 1/2', 'sale_price'=>'1190', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'NIPLE BRONCE HE-HE 3/4', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'NIPLE HID HE-HE 1/2', 'sale_price'=>'190', 'stock'=> '20'],
                 ['barcode'=>'', 'name'=>'NIPLE VALCO HE-HE 1/2', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'NIVEL ALUMINIO 14"', 'sale_price'=>'1690', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'NIVEL ALUMINIO 20"', 'sale_price'=>'2100', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'OVILLO PLASTICO CHICO ', 'sale_price'=>'690', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'PALA PUNTA HUEVO C/MANGO', 'sale_price'=>'5200', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'PASTA PULIR 300GR', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'PASTA SOLDAR 100 GRS', 'sale_price'=>'990', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'PASTA SOLDAR 50 GRS', 'sale_price'=>'690', 'stock'=> '18'],
                 ['barcode'=>'', 'name'=>'PERNO ANCLAJE 1/4 X 3', 'sale_price'=>'150', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'PERNO ANCLAJE 1/4X2 1/2', 'sale_price'=>'150', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'PERNO ANCLAJE 5/16 X 4 1/2', 'sale_price'=>'200', 'stock'=> '50'],
                 ['barcode'=>'', 'name'=>'PERNO ANCLAJE 5/16 X 3', 'sale_price'=>'150', 'stock'=> '50'],
                 ['barcode'=>'', 'name'=>'PERNO COCHE 1/4 X 1', 'sale_price'=>'40', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'PERNO COCHE 1/4 X 1 1/2', 'sale_price'=>'50', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'PERNO COCHE 1/4 X 2', 'sale_price'=>'60', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'PERNO COCHE 1/4 X 2 1/2', 'sale_price'=>'70', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'PERNO COCHE 1/4 X 3', 'sale_price'=>'90', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'PERNO COCHE 1/4 X4', 'sale_price'=>'150', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'PERNO COCHE 3/8 X 2', 'sale_price'=>'130', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'PERNO COCHE 3/8 X 2 1/2', 'sale_price'=>'160', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'PERNO COCHE 3/8 X 1 1/2', 'sale_price'=>'110', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'PERNO COCHE 3/8 X 3', 'sale_price'=>'200', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'PERNO COCHE 3/8 X 4', 'sale_price'=>'220', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'PERNO COCHE 5/16 X 1 ', 'sale_price'=>'60', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'PERNO COCHE 5/16 X 1 1/2', 'sale_price'=>'70', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'PERNO COCHE 5/16 X 2', 'sale_price'=>'90', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'PERNO COCHE 5/16 X 2 1/2', 'sale_price'=>'100', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'PERNO COCHE 5/16 X 3', 'sale_price'=>'150', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'PERNO COCHE 5/16 X 4', 'sale_price'=>'150', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'PERNO COCINA CABEZA PLANA 1/4 X 1', 'sale_price'=>'70', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'PERNO COCINA CABEZA PLANA 1/4 X 1 1/2', 'sale_price'=>'100', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'PERNO COCINA CABEZA PLANA 1/4 X 1 1/4', 'sale_price'=>'100', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'PERNO COCINA CABEZA PLANA 1/4 X 2', 'sale_price'=>'150', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'PERNO COCINA CABEZA PLANA 1/4 X 3/4', 'sale_price'=>'70', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'PERNO COCINA CABEZA PLANA 10  X 1', 'sale_price'=>'50', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'PERNO COCINA CABEZA PLANA 10 X 1 1/2', 'sale_price'=>'60', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'PERNO COCINA CABEZA PLANA 10 X 1 1/4', 'sale_price'=>'60', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'PERNO COCINA CABEZA PLANA 10 X 2 ', 'sale_price'=>'80', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'PERNO COCINA CABEZA PLANA 10 X 3/4', 'sale_price'=>'40', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'PERNO COCINA CABEZA PLANA 3/16 X 1 ', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'PERNO COCINA CABEZA PLANA 3/16 X 1 1/2', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'PERNO COCINA CABEZA PLANA 3/16 X 1 1/4 ', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'PERNO COCINA CABEZA PLANA 3/16 X 2', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'PERNO COCINA CABEZA PLANA 3/16 X 3/4 ', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'PERNO COCINA CABEZA REDONDA 1/4 X 1', 'sale_price'=>'60', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'PERNO COCINA CABEZA REDONDA 1/4 X 1 1/2', 'sale_price'=>'80', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'PERNO COCINA CABEZA REDONDA 1/4 X 1 1/4', 'sale_price'=>'70', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'PERNO COCINA CABEZA REDONDA 1/4 X 2', 'sale_price'=>'80', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'PERNO COCINA CABEZA REDONDA 1/4 X 3/4 ', 'sale_price'=>'50', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'PERNO COCINA CABEZA REDONDA 1/8 X 1 ', 'sale_price'=>'20', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'PERNO COCINA CABEZA REDONDA 1/8 X 1 1/2', 'sale_price'=>'20', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'PERNO COCINA CABEZA REDONDA 1/8 X 1 1/4', 'sale_price'=>'20', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'PERNO COCINA CABEZA REDONDA 1/8 X 2', 'sale_price'=>'30', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'PERNO COCINA CABEZA REDONDA 1/8 X 3/4 ', 'sale_price'=>'20', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'PERNO COCINA CABEZA REDONDA 3/16 X 1', 'sale_price'=>'40', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'PERNO COCINA CABEZA REDONDA 3/16 X 1 1/2', 'sale_price'=>'50', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'PERNO COCINA CABEZA REDONDA 3/16 X 1 1/4', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'PERNO COCINA CABEZA REDONDA 3/16 X 2', 'sale_price'=>'50', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'PERNO COCINA CABEZA REDONDA 3/16 X 3/4', 'sale_price'=>'30', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'PERNO HEXAGONAL  1/2 X 2', 'sale_price'=>'250', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'PERNO HEXAGONAL 1/2 X 1', 'sale_price'=>'150', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'PERNO HEXAGONAL 1/2 X 1 1/2', 'sale_price'=>'220', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'PERNO HEXAGONAL 1/2 X 2 1/2', 'sale_price'=>'300', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'PERNO HEXAGONAL 1/2 X 3', 'sale_price'=>'320', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'PERNO HEXAGONAL 1/2 X 3/4', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'PERNO HEXAGONAL 1/2 X 4', 'sale_price'=>'430', 'stock'=> '50'],
                 ['barcode'=>'', 'name'=>'PERNO HEXAGONAL 1/4 X 1', 'sale_price'=>'40', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'PERNO HEXAGONAL 1/4 X 1 1/2', 'sale_price'=>'50', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'PERNO HEXAGONAL 1/4 X 2', 'sale_price'=>'60', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'PERNO HEXAGONAL 1/4 X 2 1/2', 'sale_price'=>'70', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'PERNO HEXAGONAL 1/4 X 3', 'sale_price'=>'90', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'PERNO HEXAGONAL 1/4 X 4', 'sale_price'=>'120', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'PERNO HEXAGONAL 3/8 X 1', 'sale_price'=>'70', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'PERNO HEXAGONAL 3/8 X 1 1/2', 'sale_price'=>'100', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'PERNO HEXAGONAL 3/8 X 2', 'sale_price'=>'120', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'PERNO HEXAGONAL 3/8 X 2 1/2', 'sale_price'=>'150', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'PERNO HEXAGONAL 3/8 X 3', 'sale_price'=>'200', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'PERNO HEXAGONAL 3/8 X 3/4', 'sale_price'=>'70', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'PERNO HEXAGONAL 3/8 X 4', 'sale_price'=>'220', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'PERNO HEXAGONAL 5 / 16 X 2 1/2', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'PERNO HEXAGONAL 5/16 X 1 ', 'sale_price'=>'50', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'PERNO HEXAGONAL 5/16 X 1 1/2', 'sale_price'=>'70', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'PERNO HEXAGONAL 5/16 X 2 ', 'sale_price'=>'90', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'PERNO HEXAGONAL 5/16 X 3', 'sale_price'=>'120', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'PERNO HEXAGONAL 5/16 X 4', 'sale_price'=>'180', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'PERNO MARQUEZA 5/16 X 4', 'sale_price'=>'380', 'stock'=> '50'],
                 ['barcode'=>'', 'name'=>'PERNO MARQUEZA 5/16 X5', 'sale_price'=>'450', 'stock'=> '50'],
                 ['barcode'=>'', 'name'=>'PICAPORTE 2" FERROMAT', 'sale_price'=>'550', 'stock'=> '12'],
                 ['barcode'=>'', 'name'=>'PICAPORTE 2 1/2" FERROMAT', 'sale_price'=>'850', 'stock'=> '12'],
                 ['barcode'=>'', 'name'=>'PICAPORTE 2" BLISTER UYUS', 'sale_price'=>'590', 'stock'=> '24'],
                 ['barcode'=>'', 'name'=>'PICAPORTE 4" BLISTER UYUS', 'sale_price'=>'990', 'stock'=> '24'],
                 ['barcode'=>'', 'name'=>'PICAPORTE PLANO  21/2', 'sale_price'=>'500', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'PICAPORTE PLANO  3"', 'sale_price'=>'990', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'PICOTA PUNTA ROMA ', 'sale_price'=>'6430', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'PILETA SANIT 110/50/40     1 SALIDA', 'sale_price'=>'2590', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'PILETA SANIT 110/75/50/40      4 SALIDAS', 'sale_price'=>'3990', 'stock'=> '5'],
                 ['barcode'=>'', 'name'=>'PINTURA SPRAY ALUMINIO', 'sale_price'=>'1890', 'stock'=> '6'],
                 ['barcode'=>'', 'name'=>'PINTURA SPRAY AZUL', 'sale_price'=>'1890', 'stock'=> '6'],
                 ['barcode'=>'', 'name'=>'PINTURA SPRAY BLANCO', 'sale_price'=>'1890', 'stock'=> '6'],
                 ['barcode'=>'', 'name'=>'PINTURA SPRAY NEGRO', 'sale_price'=>'1890', 'stock'=> '6'],
                 ['barcode'=>'', 'name'=>'PINTURA SPRAY ROJO', 'sale_price'=>'1890', 'stock'=> '6'],
                 ['barcode'=>'', 'name'=>'PIOLA ORILLADORA 1.5MM', 'sale_price'=>'650', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'PIOLA ORILLADORA 2.0MM', 'sale_price'=>'1190', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'PISTOLA CALAFATERA ', 'sale_price'=>'990', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'PISTOLA CALAFATERA REFORZADA', 'sale_price'=>'2990', 'stock'=> '6'],
                 ['barcode'=>'', 'name'=>'PL. FIBROCEMENTO 4MM', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'PLANZA RECUPERADA 1/2XMTS', 'sale_price'=>'150', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'PLOMADA PESCA ESPIRAL', 'sale_price'=>'150', 'stock'=> '15'],
                 ['barcode'=>'', 'name'=>'PLATACHO 30X12', 'sale_price'=>'3690', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'PLOMADA CARPINTERA 300GRS', 'sale_price'=>'1790', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'PLOMADA CARPINTERA 600GRS', 'sale_price'=>'2590', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'POMELES 1/2  C/U', 'sale_price'=>'700', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'POMELES 3/4 C/U', 'sale_price'=>'950', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'POMELES 3/8 C/U', 'sale_price'=>'300', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'POMELES 5/8 C/U', 'sale_price'=>'850', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'PORTACANDADO 2 1/2 UYUS', 'sale_price'=>'500', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'PORTACANDADO 3 1/2 UYUS', 'sale_price'=>'990', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'PORTAELECTRODO 300 AMP', 'sale_price'=>'1990', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'PORTAELECTRODO 500 AMP', 'sale_price'=>'1990', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'PORTALAMPARA ELECTRICO BLANCO', 'sale_price'=>'890', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'POSTONES 4,5 C/PUNTA', 'sale_price'=>'990', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'POSTONES 5,5 C/PUNTA', 'sale_price'=>'1490', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'PUNTA 1 1/2 X  1/2 KG', 'sale_price'=>'1000', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'PUNTA 1 1/2 X KG', 'sale_price'=>'1990', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'PUNTO 10"', 'sale_price'=>'1590', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'REDUCCION PLANZA 3/4X1/2', 'sale_price'=>'190', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'REDUCCION SANIT 110/50 ', 'sale_price'=>'990', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'REDUCCION SANIT 110/75 ', 'sale_price'=>'1190', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'REDUCCION SANIT 50/40', 'sale_price'=>'390', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'REDUCCION SANIT 75/50', 'sale_price'=>'490', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'REGULADOR DE GAS 15 KG', 'sale_price'=>'7490', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'REMACHADORA POP', 'sale_price'=>'3700', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'REMACHES POP 3,2 X 10 ', 'sale_price'=>'10', 'stock'=> '200'],
                 ['barcode'=>'', 'name'=>'REMACHES POP 3,2 X 12', 'sale_price'=>'20', 'stock'=> '200'],
                 ['barcode'=>'', 'name'=>'REMACHES POP 3,2 X 15', 'sale_price'=>'20', 'stock'=> '200'],
                 ['barcode'=>'', 'name'=>'REMACHES POP 3,2 X 6', 'sale_price'=>'10', 'stock'=> '200'],
                 ['barcode'=>'', 'name'=>'REMACHES POP 3,2 X 8', 'sale_price'=>'10', 'stock'=> '200'],
                 ['barcode'=>'', 'name'=>'REMACHES POP 4,0 X 10', 'sale_price'=>'20', 'stock'=> '200'],
                 ['barcode'=>'', 'name'=>'REMACHES POP 4,0 X 12', 'sale_price'=>'20', 'stock'=> '200'],
                 ['barcode'=>'', 'name'=>'REMACHES POP 4,0 X 15', 'sale_price'=>'20', 'stock'=> '200'],
                 ['barcode'=>'', 'name'=>'REMACHES POP 4,0 X 6', 'sale_price'=>'20', 'stock'=> '200'],
                 ['barcode'=>'', 'name'=>'REMACHES POP 4,0 X 8', 'sale_price'=>'20', 'stock'=> '200'],
                 ['barcode'=>'', 'name'=>'REMACHES POP 4,8 X 10', 'sale_price'=>'20', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'REMACHES POP 4,8 X 12', 'sale_price'=>'20', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'REMACHES POP 4,8 X 15 ', 'sale_price'=>'20', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'REMACHES POP 4,8 X 21', 'sale_price'=>'25', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'REMACHES POP 4,8 X 25', 'sale_price'=>'30', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'REMACHES POP 4,8 X 30', 'sale_price'=>'30', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'REPUESTO CARTONERO ', 'sale_price'=>'100', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'RIEL CORREDERA 14"', 'sale_price'=>'1500', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'RIEL CORREDERA P/CAJON 14" PAR', 'sale_price'=>'1500', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'RODILLO CHIPORRO SINT 12 CM', 'sale_price'=>'1590', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'RODILLO CHIPORRO SINT 15 CM', 'sale_price'=>'1790', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'RODILLO CHIPORRO SINT 18 CM', 'sale_price'=>'1890', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'RODILLO CHIPORRO SINT 7 CM', 'sale_price'=>'1190', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'RODILLO CHIPORRO SINTETICO 22 CM.', 'sale_price'=>'2100', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'RODILLO ESPUMA 12 CM', 'sale_price'=>'1390', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'RODILLO ESPUMA 15 CM', 'sale_price'=>'1590', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'RODILLO ESPUMA 18 CM', 'sale_price'=>'1790', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'RODILLO ESPUMA 4,5 CM', 'sale_price'=>'890', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'RODILLO ESPUMA 7 CM', 'sale_price'=>'1190', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'RODILLO LANA 12 CM', 'sale_price'=>'2120', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'RODILLO LANA 18 CM', 'sale_price'=>'2480', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'SELLO ANTIFUGA WC', 'sale_price'=>'1490', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'SERRUCHO CARPINTERO 18"', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'SERRUCHO CARPINTERO 22"', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'SET ACOPLE EST/TAZA C/ESPONJA', 'sale_price'=>'1990', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'SIERRA COPA 4 PIEZAS', 'sale_price'=>'2990', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'SIFON DE LAVATORIO 1 1/4 S/CURVA', 'sale_price'=>'2190', 'stock'=> '6'],
                 ['barcode'=>'', 'name'=>'SIFON DE LAVATORIO 1 1/4 S/RECTA', 'sale_price'=>'1990', 'stock'=> '6'],
                 ['barcode'=>'', 'name'=>'SIFON LAVAPLATO 1 1/2 S/CURVA STDA', 'sale_price'=>'2290', 'stock'=> '6'],
                 ['barcode'=>'', 'name'=>'SIFON LAVAPLATO 1 1/2 S/RECTA', 'sale_price'=>'2190', 'stock'=> '6'],
                 ['barcode'=>'', 'name'=>'SIKAFLEX 11-FC GRIS', 'sale_price'=>'6990', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'SILICONA ALTA TEMPERATURA X 85 GR ROJA-GRIS', 'sale_price'=>'790', 'stock'=> '24'],
                 ['barcode'=>'', 'name'=>'SILICONA BLANCA 310 ML', 'sale_price'=>'1590', 'stock'=> '48'],
                 ['barcode'=>'', 'name'=>'SILICONA HOJALATERA 310 ML', 'sale_price'=>'2190', 'stock'=> '24'],
                 ['barcode'=>'', 'name'=>'SILICONA PINTABLE 310 ML', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'SILICONA TRANSPATENTE 310 ML', 'sale_price'=>'1590', 'stock'=> '48'],
                 ['barcode'=>'', 'name'=>'SODA CAUSTICA 1/2KG', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'SODA CAUSTICA 1KG', 'sale_price'=>'2190', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'SOLDADURA ESTAÑO BARRA 100 GRS 50%', 'sale_price'=>'1990', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'SOLDADURA ESTAÑO DISPLAY C/PASTA', 'sale_price'=>'1990', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'SOLDADURA ESTAÑO ROLLO 1/2 KG 50%', 'sale_price'=>'10590', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'SOLDADURA ESTAÑO XMTS', 'sale_price'=>'1350', 'stock'=> '8'],
                 ['barcode'=>'', 'name'=>'SOPAPA DESTAPAR WC', 'sale_price'=>'1200', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'SOPLETE GAS', 'sale_price'=>'8990', 'stock'=> '6'],
                 ['barcode'=>'', 'name'=>'SOPORTE BARRA CORTINA DOBLE ', 'sale_price'=>'1690', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'SOPORTE BARRA CORTINA SIMPLE', 'sale_price'=>'1190', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'SPLITTER 1 X 2', 'sale_price'=>'500', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'SPLITTER 1 X 3', 'sale_price'=>'600', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'TAPA SANIR 40 MM', 'sale_price'=>'290', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'TAPA SANIT 110 MM', 'sale_price'=>'590', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'TAPA SANIT 50MM', 'sale_price'=>'390', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'TAPA SANIT 75 MM ', 'sale_price'=>'490', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'TAPA TORNILLO BRONCE HE 1/2', 'sale_price'=>'470', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'TAPA TORNILLO HID HE 1/2', 'sale_price'=>'240', 'stock'=> '50'],
                 ['barcode'=>'', 'name'=>'TAPAGORRO BRONCE HI 1/2', 'sale_price'=>'670', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'TAPAGORRO BRONCE SO 1/2', 'sale_price'=>'260', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'TAPAGORRO BRONCE SO 3/4', 'sale_price'=>'560', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'TAPAGORRO COBRE 1/2', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'TAPAGORRO HID 1/2', 'sale_price'=>'150', 'stock'=> '50'],
                 ['barcode'=>'', 'name'=>'TAPAGORRO HID 25MM', 'sale_price'=>'240', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'TAPAGORRO HID HI 1/2', 'sale_price'=>'190', 'stock'=> '20'],
                 ['barcode'=>'', 'name'=>'TARUGO CLAVO 60X80 ', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'TARUGO CLAVO 8X100', 'sale_price'=>'180', 'stock'=> '50'],
                 ['barcode'=>'', 'name'=>'TARUGO CLAVO 8X60', 'sale_price'=>'130', 'stock'=> '50'],
                 ['barcode'=>'', 'name'=>'TARUGO CLAVO 8X80', 'sale_price'=>'150', 'stock'=> '50'],
                 ['barcode'=>'', 'name'=>'TARUGO INTERNIT', 'sale_price'=>'30', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'TARUGO PALOMA ', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'TARUGO PLASTICO 10MM C/U', 'sale_price'=>'30', 'stock'=> '1000'],
                 ['barcode'=>'', 'name'=>'TARUGO PLASTICO 6MM C/U', 'sale_price'=>'10', 'stock'=> '1000'],
                 ['barcode'=>'', 'name'=>'TARUGO PLASTICO 8MM C/U', 'sale_price'=>'20', 'stock'=> '1000'],
                 ['barcode'=>'', 'name'=>'TEE  COBRE 1/2', 'sale_price'=>'520', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'TEE BROCE SO-SO 3/4', 'sale_price'=>'1190', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'TEE BRONCE SO-HI 1/2', 'sale_price'=>'1190', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'TEE BRONCE SO-SO 1/2', 'sale_price'=>'650', 'stock'=> '20'],
                 ['barcode'=>'', 'name'=>'TEE HID 1"', 'sale_price'=>'420', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'TEE HID 1/2', 'sale_price'=>'150', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'TEE HID 25X3/4', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'TEE HID 3/4', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'TEE HID HI 1/2', 'sale_price'=>'350', 'stock'=> '20'],
                 ['barcode'=>'', 'name'=>'TEE PLANZA 1/2', 'sale_price'=>'190', 'stock'=> '20'],
                 ['barcode'=>'', 'name'=>'TEE PLANZA 3/4', 'sale_price'=>'390', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'TEE REGISTRO SANITARIA', 'sale_price'=>'2990', 'stock'=> '5'],
                 ['barcode'=>'', 'name'=>'TEE SANIT 110 X 40MM', 'sale_price'=>'1590', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'TEE SANIT 110MM', 'sale_price'=>'2200', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'TEE SANIT 110X50MM', 'sale_price'=>'1690', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'TEE SANIT 110X75 MM', 'sale_price'=>'1890', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'TEE SANIT 40 MM', 'sale_price'=>'590', 'stock'=> '20'],
                 ['barcode'=>'', 'name'=>'TEE SANIT 50 MM', 'sale_price'=>'690', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'TEE SANIT 75 MM', 'sale_price'=>'1290', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'TEFLON AGUA 1/2', 'sale_price'=>'200', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'TEFLON AGUA 3/4', 'sale_price'=>'300', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'TEFLON GAS 1/2', 'sale_price'=>'500', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'TENAZA 8"', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'TERMINAL BRONCE HI 1/2', 'sale_price'=>'660', 'stock'=> '25'],
                 ['barcode'=>'', 'name'=>'TERMINAL BRONCE HI 3/4', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'TERMINAL BRONCE SO- HE 1/2', 'sale_price'=>'570', 'stock'=> '50'],
                 ['barcode'=>'', 'name'=>'TERMINAL BRONCE SO-HE 3/4', 'sale_price'=>'820', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'TERMINAL HID HE 20X1/2', 'sale_price'=>'150', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'TERMINAL HID HE 25X3/4', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'TERMINAL HID HE 32X1"', 'sale_price'=>'340', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'TERMINAL HID HI 20X1/2', 'sale_price'=>'190', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'TERMINAL HID HI 25X3/4', 'sale_price'=>'340', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'TERMINAL HID HI 32X1"', 'sale_price'=>'490', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'TERMINAL PLANZA HE 1/2', 'sale_price'=>'190', 'stock'=> '20'],
                 ['barcode'=>'', 'name'=>'TERMINAL PLANZA HE 3/4', 'sale_price'=>'290', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'TERMINAL PLANZA HI 1/2', 'sale_price'=>'250', 'stock'=> '20'],
                 ['barcode'=>'', 'name'=>'TERMINAL PLANZA HI 3/4', 'sale_price'=>'390', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'TIJERA HOJALATERA AVIACION', 'sale_price'=>'2900', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'TIRADOR CROMADO 4"', 'sale_price'=>'170', 'stock'=> '12'],
                 ['barcode'=>'', 'name'=>'TIRADOR DORADO 4"', 'sale_price'=>'170', 'stock'=> '12'],
                 ['barcode'=>'', 'name'=>'TIRAFONDO 1/4 X 1', 'sale_price'=>'50', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'TIRAFONDO 1/4 X 1 1/2', 'sale_price'=>'50', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'TIRAFONDO 1/4 X 2', 'sale_price'=>'80', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'TIRAFONDO 1/4 X 2 1/2', 'sale_price'=>'100', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'TIRAFONDO 1/4 X 3', 'sale_price'=>'100', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'TIRAFONDO 1/4 X 4', 'sale_price'=>'120', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'TIRAFONDO 3/8 X 1', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'TIRAFONDO 3/8 X 1 1/2', 'sale_price'=>'120', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'TIRAFONDO 3/8 X 2', 'sale_price'=>'150', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'TIRAFONDO 3/8 X 2 1/2', 'sale_price'=>'190', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'TIRAFONDO 3/8 X 3 ', 'sale_price'=>'220', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'TIRAFONDO 3/8 X 4', 'sale_price'=>'260', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'TIRAFONDO 5/ 16 X 4', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'TIRAFONDO 5/16 X 1', 'sale_price'=>'60', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'TIRAFONDO 5/16 X 1 1/2', 'sale_price'=>'70', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'TIRAFONDO 5/16 X 2 ', 'sale_price'=>'120', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'TIRAFONDO 5/16 X 2 1/2', 'sale_price'=>'120', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'TIRAFONDO 5/16 X 3', 'sale_price'=>'150', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'TOPE RIZADO 1/2 PAR', 'sale_price'=>'150', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'TORNILLO AUTOPERFORANTE 12 X 1', 'sale_price'=>'40', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'TORNILLO AUTOPERFORANTE 12 X 1 1/2', 'sale_price'=>'50', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'TORNILLO AUTOPERFORANTE 12 X 1 1/4', 'sale_price'=>'40', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'TORNILLO AUTOPERFORANTE 12 X 2', 'sale_price'=>'50', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'TORNILLO CABEZA LENTEJA  6 X 1/2 ', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'TORNILLO CABEZA LENTEJA 6 X 1', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'TORNILLO CABEZA LENTEJA 6 X 3/4', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'TORNILLO CABEZA LENTEJA 8 X 1/2', 'sale_price'=>'10', 'stock'=> '1000'],
                 ['barcode'=>'', 'name'=>'TORNILLO CABEZA LENTEJA 8 X 1"', 'sale_price'=>'20', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'TORNILLO CABEZA LENTEJA 8 X 3/4', 'sale_price'=>'10', 'stock'=> '1000'],
                 ['barcode'=>'', 'name'=>'TORNILLO ESCUADRA 1 1/2"', 'sale_price'=>'70', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'TORNILLO ESCUADRA 2"', 'sale_price'=>'80', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'TORNILLO ROSCALATA 10 X 1', 'sale_price'=>'20', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'TORNILLO ROSCALATA 10 X 1 1/2', 'sale_price'=>'30', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'TORNILLO ROSCALATA 10 X 1 1/4', 'sale_price'=>'30', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'TORNILLO ROSCALATA 10 X 1/2 ', 'sale_price'=>'10', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'TORNILLO ROSCALATA 10 X 3/4', 'sale_price'=>'10', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'TORNILLO ROSCALATA 12 X 1', 'sale_price'=>'30', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'TORNILLO ROSCALATA 12 X 1 1/2', 'sale_price'=>'40', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'TORNILLO ROSCALATA 12 X 1/2', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'TORNILLO ROSCALATA 12 X 2', 'sale_price'=>'40', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'TORNILLO ROSCALATA 12 X 3/4', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'TORNILLO ROSCALATA 6 X 1', 'sale_price'=>'10', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'TORNILLO ROSCALATA 6 X 1 1/2', 'sale_price'=>'20', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'TORNILLO ROSCALATA 6 X 1 1/4', 'sale_price'=>'20', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'TORNILLO ROSCALATA 6 X 3/4', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'TORNILLO ROSCALATA 6X 1/2', 'sale_price'=>'10', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'TORNILLO ROSCALATA 8 X 1', 'sale_price'=>'10', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'TORNILLO ROSCALATA 8 X 1 1/2', 'sale_price'=>'30', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'TORNILLO ROSCALATA 8 X 1 1/4', 'sale_price'=>'20', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'TORNILLO ROSCALATA 8 X 1/2 ', 'sale_price'=>'10', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'TORNILLO ROSCALATA 8 X 3/4', 'sale_price'=>'10', 'stock'=> '100'],
                 ['barcode'=>'', 'name'=>'TORNILLO SPACK 3,5 X 15', 'sale_price'=>'10', 'stock'=> '144'],
                 ['barcode'=>'', 'name'=>'TORNILLO SPACK 3,5 X 20 ', 'sale_price'=>'10', 'stock'=> '144'],
                 ['barcode'=>'', 'name'=>'TORNILLO SPACK 3,5 X 25', 'sale_price'=>'10', 'stock'=> '144'],
                 ['barcode'=>'', 'name'=>'TORNILLO SPACK 3,5 X 30', 'sale_price'=>'10', 'stock'=> '144'],
                 ['barcode'=>'', 'name'=>'TORNILLO SPACK 3,5 X 40', 'sale_price'=>'10', 'stock'=> '144'],
                 ['barcode'=>'', 'name'=>'TORNILLO SPACK 4 X 30', 'sale_price'=>'20', 'stock'=> '644'],
                 ['barcode'=>'', 'name'=>'TORNILLO SPACK 4 X 45', 'sale_price'=>'20', 'stock'=> '144'],
                 ['barcode'=>'', 'name'=>'TORNILLO SPACK 4 X 50', 'sale_price'=>'20', 'stock'=> '144'],
                 ['barcode'=>'', 'name'=>'TORNILLO VOLCANITA R/ GRUESA 6 X 1  NEGRO', 'sale_price'=>'10', 'stock'=> '1000'],
                 ['barcode'=>'', 'name'=>'TORNILLO VOLCANITA R/ GRUESA 6 X 1 5/8 NEGRO', 'sale_price'=>'20', 'stock'=> '1000'],
                 ['barcode'=>'', 'name'=>'TORNILLO VOLCANITA R/ GRUESA 6 X 2 NEGRO', 'sale_price'=>'20', 'stock'=> '1000'],
                 ['barcode'=>'', 'name'=>'TORNILLO VOLCANITA R/ GRUESA 6 X 3 NEGRO', 'sale_price'=>'30', 'stock'=> '1000'],
                 ['barcode'=>'', 'name'=>'TORNILLO VOLCANITA R/ GRUESA 6 X 3/4 NEGRO', 'sale_price'=>'10', 'stock'=> '1000'],
                 ['barcode'=>'', 'name'=>'TORNILLO VOLCANITA R/GRUESA 6X1 1/4 NEGRO', 'sale_price'=>'20', 'stock'=> '1000'],
                 ['barcode'=>'', 'name'=>'TORNILLO VOLCANITA R/GRUESA 6 X 1  ZINCADO', 'sale_price'=>'10', 'stock'=> '1000'],
                 ['barcode'=>'', 'name'=>'TORNILLO VOLCANITA R/GRUESA 6 X 1 1/4  ZINCADO', 'sale_price'=>'20', 'stock'=> '1000'],
                 ['barcode'=>'', 'name'=>'TORNILLO VOLCANITA R/GRUESA 6 X 2  ZINCADO', 'sale_price'=>'20', 'stock'=> '1000'],
                 ['barcode'=>'', 'name'=>'TORNILLO VOLCANITA R/GRUESA 6 X 1 5/8 ZINCADO', 'sale_price'=>'20', 'stock'=> '1000'],
                 ['barcode'=>'', 'name'=>'TORNILLO VOLCANITA R/GRUESA 6 X 3/4  ZINCADO', 'sale_price'=>'10', 'stock'=> '1000'],
                 ['barcode'=>'', 'name'=>'TORNILLO VOLCANITA R/GRUESA 6 X 3  ZINCADO', 'sale_price'=>'30', 'stock'=> '1000'],
                 ['barcode'=>'', 'name'=>'TRAMPA LAUCHA (CHICA)', 'sale_price'=>'490', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'TRAMPA RATON (GRANDE)', 'sale_price'=>'690', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'TUBO CONDUIT 16 X 3 MTS', 'sale_price'=>'590', 'stock'=> '15'],
                 ['barcode'=>'', 'name'=>'TUBO CONDUIT 20 X 3 MTS', 'sale_price'=>'780', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'TUBO FLUORECENTE 18 WATT', 'sale_price'=>'790', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'TUBO FLUORECENTE 36 WATT', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'TUBO HID 20MM X 6 MTS', 'sale_price'=>'1890', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'TUBO HID 20MM X MTS', 'sale_price'=>'350', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'TUBO HID 25MM X 6MTS ', 'sale_price'=>'2300', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'TUBO HID 25MM X MTS ', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'TUBO SANIT 110 MM X MTS', 'sale_price'=>'1700', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'TUBO SANIT 110MM X 6MTS', 'sale_price'=>'8590', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'TUBO SANIT 40MM X 6MTS', 'sale_price'=>'3100', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'TUBO SANIT 40MM X MTS', 'sale_price'=>'720', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'TUBO SANIT 50MM X 6MTS', 'sale_price'=>'3960', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'TUBO SANIT 50MM X MTS', 'sale_price'=>'890', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'TUBO SANIT 75MM X 6 MTS', 'sale_price'=>'5990', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'TUBO SANIT 75MMX MTS', 'sale_price'=>'1200', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'TUERCA CORRIENTE 1/2', 'sale_price'=>'80', 'stock'=> '400'],
                 ['barcode'=>'', 'name'=>'TUERCA CORRIENTE 1/4', 'sale_price'=>'10', 'stock'=> '600'],
                 ['barcode'=>'', 'name'=>'TUERCA CORRIENTE 3/8', 'sale_price'=>'30', 'stock'=> '600'],
                 ['barcode'=>'', 'name'=>'TUERCA CORRIENTE 5/16', 'sale_price'=>'20', 'stock'=> '600'],
                 ['barcode'=>'', 'name'=>'TUERCA GALVANIZADA 1/4', 'sale_price'=>'20', 'stock'=> '600'],
                 ['barcode'=>'', 'name'=>'TUERCA GALVANIZADA 1/8', 'sale_price'=>'10', 'stock'=> '600'],
                 ['barcode'=>'', 'name'=>'TUERCA GALVANIZADA 3/16 ', 'sale_price'=>'10', 'stock'=> '600'],
                 ['barcode'=>'', 'name'=>'UNION AMERICANA BRONCE SO 1/2', 'sale_price'=>'1690', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'UNION AMERICANA BRONCE SO-HE 1/2', 'sale_price'=>'2280', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'UNION AMERICANA BRONE SO 3/4', 'sale_price'=>'2490', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'UNION AMERICANA HID 20MM', 'sale_price'=>'1200', 'stock'=> '10'],
                 ['barcode'=>'', 'name'=>'UNION AMERICANA HID 25MM', 'sale_price'=>'1800', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'UNION AMERICANA HID 32MM', 'sale_price'=>'1990', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'UNION AMERICANA HID HI 20MM', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'UNION DOBLE PLANZA 1/2', 'sale_price'=>'190', 'stock'=> '20'],
                 ['barcode'=>'', 'name'=>'UNION DOBRE PLNAZA 3/4', 'sale_price'=>'290', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'UÑETA LAVATORIO ', 'sale_price'=>'1500', 'stock'=> '4'],
                 ['barcode'=>'', 'name'=>'VALVULA ADMISION ESTANQUE UNIV', 'sale_price'=>'5300', 'stock'=> '6'],
                 ['barcode'=>'', 'name'=>'VALVULA ADMISION LATERAL 1/2', 'sale_price'=>'4500', 'stock'=> '6'],
                 ['barcode'=>'', 'name'=>'VALVULA ADMISION REGULABLE', 'sale_price'=>'5900', 'stock'=> '6'],
                 ['barcode'=>'', 'name'=>'VALVULA BOLA GAS 1/2', 'sale_price'=>'2640', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'VALVULA BOLA JARDIN 1/2', 'sale_price'=>'2200', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'VALVULA BOLA JARDIN 3/4', 'sale_price'=>'3120', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'VALVULA BOLA PASO 1/2', 'sale_price'=>'2100', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'VALVULA BOLA PASO 3/4', 'sale_price'=>'2070', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'VALVULA COMPACTA CEMENTAR 1/2', 'sale_price'=>'990', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'VALVULA COMPACTA HI-HI 1/2', 'sale_price'=>'990', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'VEE SANIT 110 X 110 MM', 'sale_price'=>'2690', 'stock'=> '4'],
                 ['barcode'=>'', 'name'=>'VEE SANIT 110/50', 'sale_price'=>'1750', 'stock'=> '4'],
                 ['barcode'=>'', 'name'=>'VEE SANIT 110/75', 'sale_price'=>'2180', 'stock'=> '4'],
                 ['barcode'=>'', 'name'=>'VEE SANIT 40 MM', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'VEE SANIT 50 MM', 'sale_price'=>'1290', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'VEE SANIT 75 MM', 'sale_price'=>'1450', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'VIDRIO P/MASCARA SOLDAR GRADO 10', 'sale_price'=>'150', 'stock'=> '15'],
                 ['barcode'=>'', 'name'=>'ZINC 5V 0.35X2.5MTS', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'ZINC 5V 0.35X2MTS', 'sale_price'=>'4990', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'ZINC ACAN. 0.35X2.5MTS', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'ZINC ACAN. 0.35X2MTS', 'sale_price'=>'4990', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'ZINC ACAN. 0.35X3.66MTS', 'sale_price'=>'', 'stock'=> ''],
                 ['barcode'=>'', 'name'=>'BECKRON POLVO 25 KG', 'sale_price'=>'2590', 'stock'=> '9'],
                ['barcode'=>'', 'name'=>'BECKRON POLVO 1 KG GRANEL', 'sale_price'=>'250', 'stock'=> '25'],
                ['barcode'=>'', 'name'=>'DILUYENTE SINTETICO', 'sale_price'=>'1290', 'stock'=> '10'],
                ['barcode'=>'', 'name'=>'AGUARRAS', 'sale_price'=>'1290', 'stock'=> '10'],
                ['barcode'=>'', 'name'=>'PASTA MURO 1 KG', 'sale_price'=>'790', 'stock'=> '8'],
                ['barcode'=>'', 'name'=>'ACIDO MURIATICO', 'sale_price'=>'1100', 'stock'=> '6'],
                ['barcode'=>'', 'name'=>'ARCO SIERRA', 'sale_price'=>'3390', 'stock'=> '6'],
                ['barcode'=>'', 'name'=>'CAMARA CARRETILLA', 'sale_price'=>'1490', 'stock'=> '6'],
                ['barcode'=>'', 'name'=>'HUAIPE MECANICO 1/2 KG', 'sale_price'=>'650', 'stock'=> '4']
            ];
        DB::table('products')->insert($products);
    }
}
